### PR TITLE
MODINV-423 - Excessive CPU usage in a system with no user activity

### PR DESCRIPTION
**Pull request by RuslanLavrov**
## Purpose
to provide appropriate minimal default configuration for consumers verticles for running a basic system to avoid excessive CPU usage on system idle that related to periodical poll requests performed by consumers for new messages.

## Learning
[MODINV-423](https://issues.folio.org/browse/MODINV-423)
[MODSOURMAN-454](https://issues.folio.org/browse/MODSOURMAN-454)

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
When raising pull requests, please [reference](https://wiki.folio.org/display/DD/Pull+Request+Guidelines) a JIRA issue for the project associated with the module (in this case MODINV). This is important for managing what changes were included in a particular release.

**Comment by adamdickmeiss** [comment]
Has it been verified that this fix reduces CPU usage? "periodical poll requests performed by consumers for new messages." sounds like it could be the problem.

**Review by Aliaksandr-Fedasiuk — APPROVED** [review]

**Comment by RuslanLavrov** [comment]
Yes, it has been tested on vagrant box folio/testing.

**Review by adamdickmeiss — APPROVED** [review]
Thx

**Review by OleksiiKuzminov — APPROVED** [review]

**Review by VRohach — APPROVED** [review]

**Pull request merged**
