### PR TITLE
MODINV-363 - Release-16.1.2 (backport to master)

### PR DESCRIPTION
**Pull request by khandramai**
[MODINV-363](https://issues.folio.org/browse/MODINV-363) - Release 16.1.2 (backport to master)

### CODE REVIEW

**Comment by bohdan-suprun** [comment]
Hi @khandramai, is it bug-fix release? We don't usually backport bug fix releases.

**Comment by khandramai** [comment]
@bohdan-suprun , so how to reflect NEWS.md updating in the master?

**Review by adamdickmeiss — COMMENTED** [review]
Redundant work.

**Comment by khandramai** [comment]
OK, guys. Noted. Please, review bug-fix release https://github.com/folio-org/mod-inventory/pull/284.

**Pull request closed without merging**
