### PR TITLE
MODINV-277:Disallow editing of Preceding/Succeeding fields when Instance has an underlying MARC record

### PR DESCRIPTION
**Pull request by VRohach**
1. Preceding/Succeding titles added to the INSTANCE_BLOCKED_FIELDS.
2. Preceding/Succeding titles added to the InstancesApiExamples.

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
Does this stop preceding and succeeding titles being changed in the API, or does it only inform the reference UI of the preference? 

If it does, please could a test be added to demonstrate this behaviour.

**Comment by VRohach** [comment]
> Does this stop preceding and succeeding titles being changed in the API, or does it only inform the reference UI of the preference?
> 
> If it does, please could a test be added to demonstrate this behaviour.

Hello @marcjohnson-kint ! I think that this behaviour is already demonstrated int this test-case: "canNotUpdateAnExistingMARCInstanceIfBlockedFieldsAreChanged"

**Comment by marcjohnson-kint** [comment]
> > Does this stop preceding and succeeding titles being changed in the API, or does it only inform the reference UI of the preference?
> > If it does, please could a test be added to demonstrate this behaviour.
> 
> Hello @marcjohnson-kint ! I think that this behaviour is already demonstrated in this test-case: "canNotUpdateAnExistingMARCInstanceIfBlockedFieldsAreChanged"

Does that work as well for special properties which are treated differently, like preceding and succeeding titles?

**Comment by VRohach** [comment]
> > > Does this stop preceding and succeeding titles being changed in the API, or does it only inform the reference UI of the preference?
> > > If it does, please could a test be added to demonstrate this behaviour.
> > 
> > 
> > Hello @marcjohnson-kint ! I think that this behaviour is already demonstrated in this test-case: "canNotUpdateAnExistingMARCInstanceIfBlockedFieldsAreChanged"
> 
> Does that work as well for special properties which are treated differently, like preceding and succeeding titles?

I think you are right. @OleksiiKuzminov could you please correct me, if I`m wrong?

**Comment by OleksiiKuzminov** [comment]
> Does this stop preceding and succeeding titles being changed in the API, or does it only inform the reference UI of the preference?
> 
> If it does, please could a test be added to demonstrate this behaviour.

https://github.com/folio-org/mod-inventory/blob/2401aaf6fc908d2dafa5641038029c0b884d8bf5/src/main/java/org/folio/inventory/resources/Instances.java#L206

All properties from InventoryConfigurationImpl are protected in the update method

**Pull request merged**
