### PR TITLE
MODINV-541 Remove explicit dependencies on SRM and mod-data-import-converter-storage clients

### PR DESCRIPTION
**Pull request by AivarIUsupov**
## Purpose
Calls to mod-source-record-manager and mod-data-import-converter-storage are required only to enable the Data Import part of functionality that is handled by mod-inventory. Data Import is not a core functionality, therefore it is undesirable for mod-inventory having explicit dependencies on Data Import modules. 

## Approach
Removed explicit dependencies on mod-source-record-manager and mod-data-import-converter-storage clients.

## Learning
[MODINV-541](https://issues.folio.org/browse/MODINV-541)

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
@KaterynaSenchenko @AivarIUsupov 

> Removed explicit dependencies on mod-source-record-manager and mod-data-import-converter-storage clients.

Is this the work that the Technical Council asked for yesterday?

**Review by Aliaksandr-Fedasiuk — APPROVED** [review]

**Review by RuslanLavrov — APPROVED** [review]

**Comment by KaterynaSenchenko** [comment]
Hi @marcjohnson-kint, yes, it is - we made optional the dependencies on mod-source-record-manager and mod-data-import-converter-storage interfaces, and removed the dependencies on their client libs so that the release of mod-inventory wasn't blocked by release of mentioned modules

**Comment by marcjohnson-kint** [comment]
> Hi @marcjohnson-kint, yes, it is - we made optional the dependencies on mod-source-record-manager and mod-data-import-converter-storage interfaces

How have they been made optional? There doesn't appear to be any changes to that effect in the module descriptor. Was it done in another pull request?

**Comment by marcjohnson-kint** [comment]
@KaterynaSenchenko Disregard those questions, I failed to interpret the strange way the diff was presented :-/ Apologies

**Pull request merged**
